### ISSUE TITLE
Saving past training

### ISSUE THREAD

**Issue by hjw9673** [percyliang/sempre#101]
Do we have to train every single time we want to test in "tables mode"?
Or is there a way to test without training (using training data from last time?)
If so, how can I do it?

Thank you.

**Comment by ppasupat** [comment]
After training, there should be a file named `params` generated in the output directory.
This file, which contains the model parameters, can be loaded using the command line flag `-Builder.inParamsPath path/to/params`. To avoid training, make sure `@train` is set to 0 instead of 1 (either by using `@train=0` or leaving it out).

Note that the file only contains feature weights, so to make it work properly, other options / command line flags should be kept identical to the ones used during training.

**Comment by hjw9673** [comment]
After doing so, I see only one iteration of train and test. 
However, I would really appreciate if I don't have to train at all, but to test. 

Thank you.

**Comment by ppasupat** [comment]
The final iteration of SEMPRE is always a test iteration. In this case, it tests on the training and dev datasets. No parameter update is being performed in that iteration.

**Comment by hjw9673** [comment]
Is there a way to save the output file(test/train iteration) in json format? 
Again, thanks a lot for answer previous two questions.

**Comment by ppasupat** [comment]
Try adding `-Learner.outputPredDerivations` to the command line. It should produce files containing the predictions to the output directory. The format is unfortunately not JSON though.
