### ISSUE TITLE
Why we need one more iteration If we do not train on last iteration ?

### ISSUE THREAD

**Issue by cdzhan** [percyliang/sempre#74]
Thanks in advance!

**Comment by yonatansito** [comment]
The reason is that we use an online algorithm and so after we train with
the last example we run once again on the training set to evaluate
performance on the training set. For the dev set it is guaranteed that you
will get in the last iteration the same performance as in the iteration
prior to the last one.

**Comment by cdzhan** [comment]
Do you mean we will combine the result on training set and dev set in the last iteration for development? Not only the result on dev set in the last iteration.

**Comment by yonatansito** [comment]
No.
I mean that if you want to know how the trained model does on the training
set, the last iteration is what gives you that.

**Comment by cdzhan** [comment]
Thank you for your answer, Three iteration and three times of random splits of the training set for development  are time consuming, so I choose 2 iteration. Do you everaged over the three times macro F1 scores for development?

**Comment by yonatansito** [comment]
yes.

**Comment by cdzhan** [comment]
Hi, how do you ran analysis experiments on the development set? Do you use only one thread to let the results stable? Is there only one way to let the results stable?
